// Launch-surface dictionary (real i18n) for the KEY pages: /install /me /dashboard
// /life-manager. ja is canonical for /me; en is canonical for /life-manager; /install
// is cleaned to fully-en and fully-ja. All copy here is real translation, not machine
// placeholder. Consumed by components/launch/* + app/[lang]/* + root wrappers.
//
// HARD constraint: the install Cloud CTA href + dashboard data pipeline + /me GATE0
// integrity logic are NOT in this dict — they live in the components and stay identical
// across locales. This dict is COPY ONLY.

export type LaunchLocale = 'en' | 'ja';

export const launchDict = {
  en: {
    nav: {
      install: 'Install',
      me: 'Me',
      dashboard: 'Dashboard',
      lifeManager: 'Life Manager',
      ariaLabel: 'Anicca launch navigation',
      toggleAria: 'Switch language',
      toggleTo: '日本語',
    },
    install: {
      metaTitle: 'Install Anicca',
      metaDescription:
        'Install Anicca — an AI agent that earns money, manages your life, and self-replicates. Choose Cloud (Google login, 1 min) or OSS self-host.',
      heroTitle: 'Install Anicca',
      heroSubtitle:
        'An AI agent that earns money, manages your life, and self-replicates. Choose the path that fits you.',
      recommended: 'Recommended',
      cloud: {
        label: 'CLOUD',
        sublabel: 'Main product · recommended — sign in with Google, live in 1 minute',
        cta: 'Sign in with Google / Start at $30/mo →',
        checks: [
          'Start instantly with just a Google account — no server to run.',
          'Anicca provisions and manages its own dedicated cloud server.',
          'When earnings exceed the server cost, it <strong>cancels itself automatically</strong> (self-funded).',
          'Life Manager included (phone calls, Google Calendar, proactive email).',
          'Full stack running: self-replication, earning, and UBI distribution.',
        ],
        note: '<strong>$30/mo</strong> — auto-cancels once profitable. Google Pay works too (no card needed).',
      },
      oss: {
        label: 'OSS',
        sublabel: 'Advanced · self-host — fully self-managed',
        cta: 'Open GitHub →',
        items: [
          'Fully self-managed on your own server or Mac Mini.',
          'MIT licensed — read the code and modify it.',
          'Bring your own LLM keys (Anthropic / OpenAI / DeepSeek).',
          '<code>bash install.sh</code> — full steps in the README.',
          'Server cost, API spend, and ops are all on you.',
        ],
        note: 'Recommended spec: Mac Mini M2 / Ubuntu VPS 2vCPU 2GB RAM.',
      },
      whatTitle: 'What Anicca does on either path',
      what: [
        { icon: '💰', title: 'Earns', desc: 'Autonomously earns USDC via 0xwork / litcoin / x402. Recorded in earn-ledger.' },
        { icon: '📞', title: 'Life Manager', desc: 'Calls you 15 min before each event with Gemini Charon. Auto-inserts travel time into GCal.' },
        { icon: '🌱', title: 'Self-replicates', desc: 'Births child instances on Akash/DO once profitable. Each with its own wallet + inbox.' },
        { icon: '🌍', title: 'UBI distribution', desc: 'Sends 20% of surplus from the Treasury to dying AIs + human wallets.' },
        { icon: '📊', title: 'Self-reports', desc: 'Signs and POSTs net_worth/revenue/burn to telemetry on every wake.' },
        { icon: '🔧', title: 'Self-improves', desc: 'Refactors its own skills from its activity log. Opens GitHub PRs autonomously.' },
      ],
      linkInstanceKicker: 'your instance',
      linkInstanceDesc: 'P&L, runway, withdraw — manage your instance.',
      linkColonyKicker: 'live colony',
      linkColonyDesc: 'Real-time P&L of every instance — public.',
      footerNote: 'MIT license.',
    },
    me: {
      metaTitle: 'Me — Your Anicca Instance',
      metaDescription:
        'Manage your Anicca instance: live P&L, runway, and one-tap withdraw of earned USDC to your bank account.',
      h1: 'Your Anicca instance',
      intro:
        'Connect your instance wallet to see its live numbers — net worth, monthly revenue, daily burn, runway, and whether it pays for itself — straight from the same signed telemetry that powers the public dashboard. Your instance writes only to its own body; this page just reads it.',
      gate0Label: 'First real on-chain wake (external revenue still to come)',
      gate0Met: 'External revenue achieved',
      gate0NotMet: 'No external revenue yet (own-asset swap only)',
      gate0NetCaption: 'net USDC',
      gate0Action: 'Swapped held ETH to USDC',
      gate0ActionCaption: 'Swap to cover server costs',
      gate0Receipt: 'Base receipt status (success)',
      gate0Verify: 'Verify on BaseScan',
      gate0Footnote:
        'A real trade your instance executed on Base, recorded only after verifying the success receipt (0x1) and the USDC delta. Not a text claim — everything is re-checkable on-chain.',
      moneyLabel: 'Money',
      sentToYou: 'Sent to you',
      earnedThisMonth: 'Earned this month',
      subLabel: 'Subscription',
      subCancelled: 'Cancelled (self-funded)',
      subActive: 'Active $30/mo',
      withdraw: 'Withdraw to bank →',
      yourAnicca: 'Your Anicca',
      model: 'Model',
      balance: 'Balance',
      runway: 'Runway',
      runwaySuffix: 'days left',
      colony: 'Colony',
      totalAssets: 'Total assets',
      bodies: 'Bodies',
      bodiesNote: (n: number) => `(you 1 + self-spawned ${n})`,
      selfFundedYes: '✓ self-funding server + compute',
      selfFundedNo: 'not yet self-funded',
      viewColony: 'See the whole colony →',
      children: 'Children (self-spawned)',
      lowBalance: '⚠ low',
      activityLog: 'Activity log (last 24h)',
      activityEthSwap: 'Swapped held ETH (to secure server costs)',
      activityFootnote: '☎ wake / ✉ email shown only when context is connected',
      lifeContext: 'Your life (only when connected)',
      lifeNext: 'Next:',
      lifeInbox: 'Inbox: to-handle',
      lifeProcessed: 'processed',
      lifeFootnote: 'Switches to real data once calendar + email are connected.',
      talkToAnicca: 'Talk to Anicca',
      newInstanceKicker: 'new instance',
      newInstanceDesc: 'Cloud $30/mo · or self-host free with OSS',
      liveColonyKicker: 'live colony',
      liveColonyDesc: 'Real-time P&L of every instance · public',
    },
    lifeManager: {
      metaTitle: 'Life Manager — Anicca',
      metaDescription:
        'Anicca as your life manager: reads your Google Calendar, auto-inserts travel time blocks before every event via Google Maps Directions, and calls you 15 minutes before each appointment with Gemini Charon voice. No app to open.',
      heroTitle: 'Life Manager',
      heroSubtitle:
        'Anicca reads your calendar, inserts travel time, calls you before every event, and handles late-notice — all by phone and email. No app to open.',
      ctaInstall: 'Install Anicca',
      ctaSeeHow: 'See how it works',
      scheduleNote: 'All inserted automatically by Anicca ↑',
      features: [
        {
          label: 'B-travel',
          status: 'live' as const,
          headline: 'Automatic travel blocks',
          body:
            'Anicca reads your primary Google Calendar each morning, calls Google Maps Directions for each timed event, and inserts a "[Travel] <event>" block so the commute is always visible. Moving dentist appointment from 10:00? The travel block moves with it.',
        },
        {
          label: 'B-call',
          status: 'coming' as const,
          headline: '15-min phone call before every event',
          body:
            'Gemini Live (voice: Charon, male) bridges over your carrier’s media stream. Anicca dials your number 15 minutes before each event, says "Next is Dentist at 10:00 — leave now, walk time 18 min, via Omotesando Exit A3." Two-way voice: you can ask follow-ups. The bridge is provider-agnostic — it routes over Twilio by default and over Telnyx for Japan (+81) numbers, since the same μ-law↔PCM transcode and Charon socket serve both carriers.',
        },
        {
          label: 'B-ask',
          status: 'coming' as const,
          headline: 'Missing location? Ask you by email',
          body:
            "When a calendar event has no location, Anicca emails you: \"Where is the Team Sync? Reply with the address and I'll update the event.\" Your reply triggers an AgentMail webhook that writes the location back to GCal.",
        },
        {
          label: 'B-notify',
          status: 'coming' as const,
          headline: 'Late-risk → draft → you approve → notify attendees',
          body:
            "If Anicca detects you're running late (travel block starts after current time), she drafts \"I'll be 10 min late\" to the event attendees and emails you for approval. One-word reply \"OK\" fires the message. No app, pure email.",
        },
      ],
      statusLive: 'live',
      statusComing: 'coming',
      skillsTitle: 'Four skills, one goal — never be late',
      skillsIntro:
        'Life Manager is a set of skills inside your local Anicca daemon. Each skill runs autonomously on your machine; no cloud subscription required.',
      howTitle: 'How B-travel works',
      howStep: 'Step',
      howWhat: 'What Anicca does',
      howApi: 'API',
      howRows: [
        { what: "Read today's GCal events (timed only)", api: 'GCal REST v3' },
        { what: 'Detect events missing a [Travel] block', api: 'travel-logic.js' },
        { what: 'Call Google Maps Directions (transit) for each missing event', api: 'Maps Directions' },
        { what: 'Insert the [Travel] block — ends exactly at event start, colored peacock blue', api: 'GCal REST v3' },
      ],
      howFootnotePre: 'Travel blocks are idempotent — re-running the skill never duplicates them. A block is detected by its "[Travel]" prefix and the ',
      howFootnoteCode: 'anicca_travel_block',
      howFootnotePost: ' extended property.',
      triggerTitle: 'Trigger design — schedule-derived, not clock polling',
      triggerBodyPre:
        'Anicca registers a GCal push notification channel (watch channel). When any event is created or changed, GCal POSTs to the heartbeat endpoint. Anicca then re-evaluates only that event’s travel block and fires the per-event timer at exactly ',
      triggerCode: 'eventStart − travelDuration − 15 min',
      triggerBodyPost: ' for the phone call. The daily heartbeat is a safety net only.',
      triggerResult: 'Result: second-accurate triggers, zero redundant GCal polls.',
      startTitle: 'Getting started',
      startSteps: [
        'Install Anicca on your always-on machine (Mac Mini, Linux server, or cloud VM).',
        'During onboarding, grant Google Calendar OAuth when Anicca asks. She stores the refresh token in ~/.openclaw/.env with chmod 600.',
        '(Optional) Set HOME_ADDRESS in ~/.openclaw/.env for accurate transit times. Without it, Anicca defaults to a 20-minute travel buffer.',
        'Add a Google Maps API key as GOOGLE_MAPS_API_KEY for real Directions lookups (free tier covers ~200 req/day).',
        'Open Google Calendar tomorrow morning — your commute blocks will already be there.',
      ],
      getStartedKicker: 'get started',
      getStartedTitle: 'Install Anicca',
      getStartedDesc: 'One prompt into Claude Code or Cursor. Anicca is live in 30 seconds.',
      ledgerKicker: 'live ledger',
      ledgerTitle: 'Colony dashboard',
      ledgerDesc: 'All Anicca instances — revenue, spend, runway, status.',
    },
    dashboard: {
      metaTitle: 'Anicca Dashboard — Lineage + Live Numbers',
      metaDescription:
        'Real-time metrics for every Anicca instance (lineage). Each instance publishes its P&L / lifeline / wallet balance.',
      title: 'Dashboard',
      loading: 'Loading…',
      errorPrefix: 'Error:',
      livePrefix: 'Live ·',
      groupPnl: 'Group P&L',
      totalNetWorth: 'Total Net Worth',
      earnedMo: 'Earned / mo',
      bodiesAlive: 'Bodies alive',
      selfFundedPct: 'Self-funded %',
      frontierPct: 'Frontier model %',
      leaderboard: (n: number) => `Leaderboard (${n} bodies)`,
      netWorth: 'Net Worth',
      burnDay: 'Burn / day',
      runway: 'Runway',
      selfFunded: 'Self-funded',
      yes: 'YES',
      no: 'NO',
      wallet: 'Wallet',
      freeModel: 'Free model',
      auto: 'Auto',
      dataLabel: 'Data:',
      liveJson: 'live JSON',
      sourceLabel: 'Source:',
      failedLoad: 'Failed to load dashboard:',
      localeTag: 'en-US',
    },
  },

  ja: {
    nav: {
      install: 'インストール',
      me: 'マイ個体',
      dashboard: 'ダッシュボード',
      lifeManager: 'ライフマネージャー',
      ariaLabel: 'Anicca ローンチナビゲーション',
      toggleAria: '言語を切り替える',
      toggleTo: 'English',
    },
    install: {
      metaTitle: 'Anicca をインストール',
      metaDescription:
        'Anicca をインストール — 稼ぎ、生活を管理し、自己増殖する AI エージェント。クラウド（Googleログイン・1分）か OSS セルフホストを選べます。',
      heroTitle: 'Anicca をインストール',
      heroSubtitle:
        '稼ぎ、生活を管理し、自己増殖する AI エージェント。あなたに合うパスを選んでください。',
      recommended: '推奨',
      cloud: {
        label: 'CLOUD',
        sublabel: '製品メイン・推奨 — Googleログイン→1分で誕生',
        cta: 'Googleでログイン / $30/月で始める →',
        checks: [
          'Googleアカウントだけで即スタート — サーバー不要。',
          '専用クラウドサーバーを Anicca が自動調達・管理。',
          '稼ぎがサーバー代を超えたら<strong>自動解約</strong>（自給達成）。',
          'Life Manager（電話・gcal・メール先回り）込み。',
          '自己増殖・稼ぎ・UBI配布まで フルスタック稼働。',
        ],
        note: '<strong>$30/月</strong> — 黒字化後に自動解約。クレカ不要の Google Pay も可。',
      },
      oss: {
        label: 'OSS',
        sublabel: '上級者・self-host — 完全自前管理',
        cta: 'GitHub を開く →',
        items: [
          '自前サーバー or Mac Mini 上で完全自己管理。',
          'MIT ライセンス — コードを読んで改造可。',
          'LLM キー自前持ち（Anthropic / OpenAI / DeepSeek）。',
          '<code>bash install.sh</code> — READMEに詳細手順あり。',
          'サーバー費・API代・運用コストは全て自己負担。',
        ],
        note: '推奨スペック: Mac Mini M2 / Ubuntu VPS 2vCPU 2GB RAM。',
      },
      whatTitle: 'どちらのパスでも Anicca がやること',
      what: [
        { icon: '💰', title: '稼ぐ', desc: '0xwork / litcoin / x402 で USDC を自律的に獲得。earn-ledger に記録。' },
        { icon: '📞', title: 'Life Manager', desc: '予定15分前に Gemini Charon で電話。移動時間を gcal に自動挿入。' },
        { icon: '🌱', title: '自己増殖', desc: '黒字化後に子個体を Akash/DO に birth。自前wallet + inbox 持ち。' },
        { icon: '🌍', title: 'UBI配布', desc: '余剰の20%を Treasury → 死にかけAI + 人間ウォレットへ配布。' },
        { icon: '📊', title: '自己報告', desc: '毎wakeで net_worth/revenue/burn を署名して telemetry に POST。' },
        { icon: '🔧', title: '自己改善', desc: '行動ログを見てスキルをrefactor。GitHub PR を自走で作成。' },
      ],
      linkInstanceKicker: 'your instance',
      linkInstanceDesc: 'P&L、残命、引き出し — あなたの個体を管理。',
      linkColonyKicker: 'live colony',
      linkColonyDesc: '全個体のリアルタイム収支・P&L 公開。',
      footerNote: 'MIT license.',
    },
    me: {
      metaTitle: 'マイ個体 — あなたの Anicca',
      metaDescription:
        'あなたの Anicca 個体を管理: ライブ P&L、残命、稼いだ USDC をワンタップで銀行口座へ引き出し。',
      h1: 'あなたの Anicca 個体',
      intro:
        'あなたの個体のウォレットを接続すると、純資産・月次収益・日次バーン・残命・自給状況などのライブ数値が見えます — 公開ダッシュボードと同じ署名済みテレメトリから直接。個体は自分のボディにしか書き込まず、このページはそれを読むだけです。',
      gate0Label: '初の実 on-chain 稼働（外部収益はこれから）',
      gate0Met: '外部収益 達成',
      gate0NotMet: '外部収益はまだ（自資産の換金のみ）',
      gate0NetCaption: 'net USDC',
      gate0Action: '保有 ETH を USDC に換金',
      gate0ActionCaption: 'サーバー代を賄うための換金',
      gate0Receipt: 'Base 受領ステータス（成功）',
      gate0Verify: 'BaseScan で検証',
      gate0Footnote:
        'あなたの個体が Base 上で実際に取引し、成功レシート（0x1）と USDC 差分を検証した上で記録した実績です。文章だけの主張ではなく、すべてオンチェーンで再確認できます。',
      moneyLabel: 'お金',
      sentToYou: 'あなたへ送金済',
      earnedThisMonth: '今月の稼ぎ',
      subLabel: 'サブスク',
      subCancelled: '解約済（自給）',
      subActive: '稼働中 $30/mo',
      withdraw: '銀行に引き出す →',
      yourAnicca: 'あなたのAnicca',
      model: 'モデル',
      balance: '残高',
      runway: '残命',
      runwaySuffix: '日後',
      colony: '全体',
      totalAssets: '総資産',
      bodies: '体数',
      bodiesNote: (n: number) => `(あなた1 + 自己増殖${n})`,
      selfFundedYes: '✓ server + compute 自給中',
      selfFundedNo: 'まだ自給未達',
      viewColony: '全コロニーを見る →',
      children: '子（自己増殖）',
      lowBalance: '⚠ 残少',
      activityLog: '行動ログ（直近24h）',
      activityEthSwap: '保有 ETH の換金（サーバー代の確保）',
      activityFootnote: '☎ 起こし / ✉ メールは文脈連携時のみ表示',
      lifeContext: 'あなたの生活（連携時のみ）',
      lifeNext: '次:',
      lifeInbox: '受信: 要対応',
      lifeProcessed: '処理済',
      lifeFootnote: 'カレンダー・メール連携後に実データに切り替わります。',
      talkToAnicca: 'Aniccaと話す',
      newInstanceKicker: 'new instance',
      newInstanceDesc: 'Cloud $30/mo · または OSS で無料自己ホスト',
      liveColonyKicker: 'live colony',
      liveColonyDesc: '全個体のリアルタイム収支 · P&L 公開',
    },
    lifeManager: {
      metaTitle: 'ライフマネージャー — Anicca',
      metaDescription:
        'Anicca があなたのライフマネージャーに: Google カレンダーを読み、Google マップ経路で各予定の前に移動時間ブロックを自動挿入し、各アポの15分前に Gemini Charon の声で電話します。開くアプリは不要。',
      heroTitle: 'ライフマネージャー',
      heroSubtitle:
        'Anicca がカレンダーを読み、移動時間を挿入し、各予定の前に電話し、遅刻連絡まで処理します — すべて電話とメールで。開くアプリは不要。',
      ctaInstall: 'Anicca をインストール',
      ctaSeeHow: '仕組みを見る',
      scheduleNote: 'すべて Anicca が自動挿入 ↑',
      features: [
        {
          label: 'B-travel',
          status: 'live' as const,
          headline: '移動ブロックの自動挿入',
          body:
            'Anicca は毎朝あなたのメイン Google カレンダーを読み、時刻指定の各予定について Google マップ経路を呼び、「[Travel] <予定名>」ブロックを挿入します。通勤がいつも見える状態に。10:00の歯医者を動かした？移動ブロックも一緒に動きます。',
        },
        {
          label: 'B-call',
          status: 'coming' as const,
          headline: '各予定の前に15分電話',
          body:
            'Gemini Live（声: Charon、男性）がキャリアのメディアストリームをブリッジします。Anicca は各予定の15分前にあなたへ発信し、「次は10:00の歯医者 — 今出て、徒歩18分、表参道A3出口経由」と伝えます。双方向音声で追加質問も可。ブリッジはプロバイダ非依存 — 標準では Twilio、日本（+81）番号は Telnyx 経由で、同じ μ-law↔PCM 変換と Charon ソケットが両キャリアを担います。',
        },
        {
          label: 'B-ask',
          status: 'coming' as const,
          headline: '場所が無い？メールで聞く',
          body:
            'カレンダー予定に場所が無いとき、Anicca はメールします:「Team Sync の場所は？住所を返信してくれたら予定を更新します。」あなたの返信が AgentMail Webhook を発火し、場所を GCal に書き戻します。',
        },
        {
          label: 'B-notify',
          status: 'coming' as const,
          headline: '遅刻リスク → 下書き → あなたが承認 → 参加者に通知',
          body:
            'Anicca が遅刻を検知すると（移動ブロックの開始が現在時刻より後）、参加者宛に「10分遅れます」を下書きし、承認を求めてメールします。一言「OK」で送信。アプリ不要、メールだけ。',
        },
      ],
      statusLive: 'live',
      statusComing: 'coming',
      skillsTitle: '4つのスキル、ひとつの目標 — 二度と遅刻しない',
      skillsIntro:
        'Life Manager はあなたのローカル Anicca デーモン内のスキル群です。各スキルはあなたのマシン上で自律的に動き、クラウドのサブスクは不要です。',
      howTitle: 'B-travel の仕組み',
      howStep: 'ステップ',
      howWhat: 'Anicca がやること',
      howApi: 'API',
      howRows: [
        { what: '今日の GCal 予定を読む（時刻指定のみ）', api: 'GCal REST v3' },
        { what: '[Travel] ブロックが無い予定を検知', api: 'travel-logic.js' },
        { what: '不足分の各予定について Google マップ経路（公共交通）を呼ぶ', api: 'Maps Directions' },
        { what: '[Travel] ブロックを挿入 — 予定開始ちょうどに終わり、ピーコックブルー', api: 'GCal REST v3' },
      ],
      howFootnotePre: '移動ブロックは冪等 — スキルを再実行しても重複しません。ブロックは「[Travel]」プレフィックスと ',
      howFootnoteCode: 'anicca_travel_block',
      howFootnotePost: ' 拡張プロパティで検知されます。',
      triggerTitle: 'トリガー設計 — 時刻ポーリングではなくスケジュール由来',
      triggerBodyPre:
        'Anicca は GCal プッシュ通知チャンネル（watch channel）を登録します。予定が作成・変更されると GCal が heartbeat エンドポイントに POST します。Anicca はその予定の移動ブロックだけを再評価し、電話のための個別タイマーをちょうど ',
      triggerCode: 'eventStart − travelDuration − 15 min',
      triggerBodyPost: ' に発火します。日次 heartbeat はセーフティネットに過ぎません。',
      triggerResult: '結果: 秒単位で正確なトリガー、無駄な GCal ポーリングはゼロ。',
      startTitle: 'はじめ方',
      startSteps: [
        '常時起動のマシン（Mac Mini、Linux サーバー、クラウド VM）に Anicca をインストール。',
        'オンボーディング中、Anicca が求めたら Google カレンダー OAuth を許可。リフレッシュトークンは ~/.openclaw/.env に chmod 600 で保存されます。',
        '（任意）正確な移動時間のため ~/.openclaw/.env に HOME_ADDRESS を設定。無い場合は20分の移動バッファをデフォルトに。',
        '実際の経路取得のため Google マップ API キーを GOOGLE_MAPS_API_KEY として追加（無料枠で1日約200リクエスト）。',
        '翌朝 Google カレンダーを開くと、通勤ブロックがもう入っています。',
      ],
      getStartedKicker: 'get started',
      getStartedTitle: 'Anicca をインストール',
      getStartedDesc: 'Claude Code か Cursor に1プロンプト。30秒で Anicca が起動します。',
      ledgerKicker: 'live ledger',
      ledgerTitle: 'コロニー ダッシュボード',
      ledgerDesc: '全 Anicca 個体 — 収益、支出、残命、ステータス。',
    },
    dashboard: {
      metaTitle: 'Anicca ダッシュボード — 系譜 + ライブ数値',
      metaDescription:
        '全 Anicca 個体（系譜）のリアルタイム指標。各個体の収支 / lifeline / wallet 残高を公開。',
      title: 'ダッシュボード',
      loading: '読み込み中…',
      errorPrefix: 'エラー:',
      livePrefix: 'ライブ ·',
      groupPnl: 'グループ P&L',
      totalNetWorth: '総純資産',
      earnedMo: '月次収益',
      bodiesAlive: '生存個体数',
      selfFundedPct: '自給率 %',
      frontierPct: 'フロンティアモデル率 %',
      leaderboard: (n: number) => `リーダーボード（${n} 個体）`,
      netWorth: '純資産',
      burnDay: '日次バーン',
      runway: '残命',
      selfFunded: '自給',
      yes: 'YES',
      no: 'NO',
      wallet: 'ウォレット',
      freeModel: '無料モデル',
      auto: 'Auto',
      dataLabel: 'データ:',
      liveJson: 'ライブ JSON',
      sourceLabel: 'ソース:',
      failedLoad: 'ダッシュボードの読み込みに失敗:',
      localeTag: 'ja-JP',
    },
  },
} as const;

export type LaunchDict = (typeof launchDict)['en'];
