export const metadata = { title: 'Privacy Policy | BreathCalm - Reset Anxiety in 6 Minutes' };

export default function BreathCalmPrivacyEN() {
  return (
    <main className="container mx-auto max-w-3xl px-4 py-24">
      <h1 className="text-3xl font-bold text-foreground">Privacy Policy</h1>
      <p className="mt-6 text-muted-foreground">
        This policy describes how we handle user data, including personal information, in the BreathCalm iOS app (the &quot;Service&quot;).
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">1. Business Information</h2>
      <p className="mt-3 text-muted-foreground">Daisuke Narita (Individual Business Owner) / keiodaisuke@gmail.com</p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">2. Scope of Application</h2>
      <p className="mt-3 text-muted-foreground">
        This policy applies to the Service and related support communications. It also applies to our website pages that link to this policy.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">3. Information We Collect</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Device identifiers (e.g., identifierForVendor / device-id) used for basic functionality and fraud/abuse prevention</li>
        <li>Breathing session data (session type, duration, mood scores before/after) stored locally on device</li>
        <li>In-app settings and preferences (e.g., notification preferences, streak data)</li>
        <li>App usage/analytics events (e.g., session starts, completions, paywall interactions)</li>
        <li>Subscription status information (managed via App Store / RevenueCat)</li>
        <li>Support communications (e.g., emails you send to our support address)</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">4. Main Collection Methods</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Information you enter in the app (mood scores, session preferences)</li>
        <li>Information generated by your interactions with the app (events/logs)</li>
        <li>Information received from the App Store and our subscription infrastructure (RevenueCat)</li>
        <li>Support inquiries sent to our support desk</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">5. Purpose of Use</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Provide and improve the Service</li>
        <li>Deliver reminders you opt into and measure engagement to improve them</li>
        <li>Manage subscriptions and entitlement status</li>
        <li>Analytics, debugging, and security measures</li>
        <li>Respond to support inquiries and send important notices</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">6. Third-Party Provision and Outsourcing</h2>
      <p className="mt-3 text-muted-foreground">
        We use the following vendors to operate the Service. Information may be transmitted to them as necessary for service provision.
      </p>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Apple (App Store billing, SKAdNetwork attribution, and related platform services)</li>
        <li>RevenueCat (subscription/entitlement management)</li>
        <li>Mixpanel (product analytics)</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">7. Data Storage</h2>
      <p className="mt-3 text-muted-foreground">
        Breathing session data, mood scores, and streak information are stored locally on your device. They are not uploaded to our servers. Your wellness data stays private.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">8. Data We Do Not Collect</h2>
      <p className="mt-3 text-muted-foreground">
        The Service does not access HealthKit data, motion/activity data, or Screen Time data. Breathing session records are stored locally and are not transmitted to our servers.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">9. Retention Period and Deletion</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Session data: Stored locally on your device. Deleted when the app is removed</li>
        <li>Identifiers on device: Reset when the app is deleted (IDFV behavior)</li>
        <li>Support history: Stored for a reasonable period to respond and maintain records</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">10. Security Measures</h2>
      <ul className="mt-3 list-disc pl-6 text-foreground space-y-2">
        <li>Secure communication (HTTPS/TLS)</li>
        <li>Session data stored only on-device (no server transmission)</li>
        <li>Appropriate access controls and operational monitoring</li>
      </ul>

      <h2 className="mt-10 text-xl font-semibold text-foreground">11. User Rights</h2>
      <p className="mt-3 text-muted-foreground">
        You may request access to, correction of, or deletion of your personal data by contacting us at keiodaisuke@gmail.com. Requests will be handled within a reasonable period.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">12. Children</h2>
      <p className="mt-3 text-muted-foreground">
        The Service is not directed to children under 13. We do not knowingly collect personal information from children under 13.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">13. Policy Updates</h2>
      <p className="mt-3 text-muted-foreground">
        We may update this policy as the Service evolves. Material changes will be communicated via in-app notice or email. Continued use of the Service after changes constitutes acceptance.
      </p>

      <h2 className="mt-10 text-xl font-semibold text-foreground">14. Contact</h2>
      <p className="mt-3 text-muted-foreground">
        For questions or concerns about this policy, contact: keiodaisuke@gmail.com
      </p>

      <p className="mt-10 text-sm text-muted-foreground">Last updated: February 2026</p>

      <div className="mt-8 border-t border-border pt-6 text-sm text-muted-foreground">
        <a href="/breath-calm/privacy/ja" className="underline hover:text-foreground">日本語版プライバシーポリシー</a>
        {' · '}
        <a href="/breath-calm/" className="underline hover:text-foreground">Back to BreathCalm</a>
      </div>
    </main>
  );
}
