default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_OPT_OUT_CRASH_REPORTING"] = "1"
    ENV["FASTLANE_SKIP_UPDATE_CHECK"] = "1"
  end

  desc "Run unit tests"
  lane :test do
    scan(
      scheme: "DeskStretch",
      devices: ["iPhone 17 Pro"],
      clean: true,
      code_coverage: true
    )
  end

  desc "Build for testing"
  lane :build do
    build_app(
      scheme: "DeskStretch",
      skip_archive: true,
      skip_codesigning: true,
      destination: "generic/platform=iOS Simulator"
    )
  end

  desc "Build for simulator"
  lane :build_for_simulator do
    build_app(
      scheme: "DeskStretch",
      configuration: "Debug",
      skip_archive: true,
      skip_codesigning: true,
      destination: "platform=iOS Simulator,name=iPhone 17 Pro"
    )
  end
end
