default_platform(:ios)

platform :ios do
  desc "Set app version"
  lane :set_version do |options|
    version = options[:version]
    increment_version_number(
      version_number: version,
      xcodeproj: "AffirmFlow.xcodeproj"
    )
    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "AffirmFlow.xcodeproj"
    )
  end

  desc "Run tests"
  lane :test do
    run_tests(
      scheme: "AffirmFlow",
      device: "iPhone 17 Pro",
      clean: true
    )
  end

  desc "Build for App Store"
  lane :build do
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "AffirmFlow.xcodeproj",
      team_id: "S5U8UH3JLJ",
      code_sign_identity: "iPhone Distribution",
      targets: ["AffirmFlow"],
      profile_uuid: "6cdcc881-a7dc-4c03-898e-7e87aaa3ed2b"
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "AffirmFlow.xcodeproj",
      team_id: "S5U8UH3JLJ",
      code_sign_identity: "iPhone Distribution",
      targets: ["AffirmFlowWidget"],
      profile_uuid: "6e642f98-6e38-4c17-9691-7c7048f72dd6"
    )
    build_app(
      scheme: "AffirmFlow",
      output_directory: "./build",
      output_name: "AffirmFlow.ipa",
      export_method: "app-store",
      clean: true,
      export_options: {
        signingStyle: "manual",
        provisioningProfiles: {
          "com.anicca.affirmflow" => "AffirmFlow AppStore",
          "com.anicca.affirmflow.widget" => "AffirmFlow Widget AppStore"
        }
      }
    )
  end

  desc "Build for simulator"
  lane :build_for_simulator do
    build_app(
      scheme: "AffirmFlow",
      destination: "generic/platform=iOS Simulator",
      configuration: "Debug",
      skip_archive: true
    )
  end

  desc "Build for device"
  lane :build_for_device do
    build_app(
      scheme: "AffirmFlow",
      export_method: "development",
      output_directory: "./build",
      output_name: "AffirmFlow-dev.ipa",
      xcargs: "-allowProvisioningUpdates"
    )

    sh("ios-deploy --bundle ../build/AffirmFlow-dev.ipa || echo 'No device connected'")
  end
end
